version: "3.9"
services:
  demand_management:
    build: .
    ports:
      - "8888:8888"
    command: marimo edit demand_management.py --host=0.0.0.0 --port=8888 --token-password=AxLyv26QD6g_LC5_Mu2sxw

  demand_management_live:
    build: .
    ports:
      - "9999:9999"
    command: marimo edit demand_management_live.py --host=0.0.0.0 --port=9999 --token-password=AxLyv26QD6g_LC5_Mu2sxw

  inventory_management:
    build: .
    ports:
      - "7777:7777"
    command: marimo edit inventory_management.py --host=0.0.0.0 --port=7777 --token-password=AxLyv26QD6g_LC5_Mu2sxw
